telegram_token: ""
openai_api_key: ""
use_mongodb: true
mongodb_uri: ""
allowed_telegram_usernames: []
new_dialog_timeout: 600
enable_message_streaming: true
return_n_generated_images: 1
n_choices: 1
